language: php

php:
  - "7.1"
  - "7.2"
  - "7.3"

before_script:
  - composer install --prefer-dist --dev

after_script:
  - php vendor/bin/php-coveralls -v
  - php vendor/bin/phpcs --standard=PSR12 src/ test/
